/**
 * Source for the opencode plugin we drop into the per-run tmpdir at
 * `<XDG_CONFIG_HOME>/opencode/plugin/pullfrog-events.ts`. The harness already
 * redirects `XDG_CONFIG_HOME` to `ctx.tmpdir/.config` (see `opencode.ts`
 * `homeEnv`), so opencode's auto-discovery scans the tmpdir, never the user's
 * working tree. opencode's `Global.Path.config` resolves to
 * `path.join(xdgConfig, "opencode")` and the config layer auto-discovers
 * plugins from every directory in its scan list — including
 * `Global.Path.config` — by globbing `{plugin,plugins}/*.{ts,js}` via
 * `ConfigPlugin.load(dir)`.
 *
 * We MUST NOT write into the user's repo working tree. The repo is a checkout
 * the agent operates on; only the agent's own tools (gated by
 * `OPENCODE_PERMISSION`) may modify it. The whole reason we redirect HOME and
 * XDG_CONFIG_HOME is so harness-side files (config, plugins, scratch state)
 * land in the tmpdir.
 *
 * Why the events plugin exists: opencode's `task` tool runs subagents
 * in-process and the CLI's `cli/cmd/run.ts` event loop filters
 * `part.sessionID !== sessionID`, so subagent-internal `message.part.updated`
 * events are silently discarded before reaching our parent NDJSON stream.
 * plugins, by contrast, receive EVERY bus event via `bus.subscribeAll()`
 * regardless of session.
 *
 * The events plugin re-emits every relevant bus event onto opencode's stdout
 * as a single JSON line wrapped in a sentinel envelope. our `runOpenCode`
 * parser recognises the envelope, unpacks it, and routes the inner part
 * through the existing handlers with a per-session label from `SessionLabeler`
 * so each subagent's tool calls / text appear inline alongside the
 * orchestrator's.
 *
 * The subagent gate (the `tool.execute.before` hook that hard-blocks
 * state-mutating MCP tool calls from a subagent session) lives in a SEPARATE
 * plugin — `buildOpencodeSubagentGateSource` below — because it's the
 * load-bearing security fence and must ship into both opencode harnesses,
 * whereas this events re-emitter is only needed by the legacy `opencode.ts`
 * CLI-parsing path (the active `opencode.ts` reads subagent events directly
 * off the SDK event stream, so it installs ONLY the gate plugin). Deny-list
 * source of truth: `action/agents/subagentToolGates.ts`.
 *
 * Dumb plugin / smart parent split: the events plugin emits every part for
 * every session. the parent dedupes against the orchestrator's own session id
 * (which it already knows from the `init` event). this keeps the plugin trivial
 * and keeps the per-session attribution logic on the parent side where the
 * SessionLabeler already lives.
 *
 * Event-name prefixing: the wrapped event-type sentinel is
 * `pullfrog_bus_event` — picked to be unmistakably ours so a future opencode
 * release that introduces a coincidentally-named event type won't collide.
 */

export const KATAK_BUS_EVENT_TYPE = "pullfrog_bus_event" as const;

export const KATAK_OPENCODE_PLUGIN_FILENAME = "pullfrog-events.ts" as const;

export const KATAK_OPENCODE_GATE_PLUGIN_FILENAME = "pullfrog-subagent-gate.ts" as const;

/**
 * Source written verbatim to `<XDG_CONFIG_HOME>/opencode/plugin/pullfrog-events.ts`.
 *
 * - Structural typing only (no runtime import of `@opencode-ai/plugin`):
 *   opencode installs that dep into the directory containing the plugin
 *   alongside discovery, but a) the dep isn't required for the structural
 *   shape we use, and b) keeping zero imports avoids any module-resolution
 *   coupling to opencode's plugin-loader internals across versions.
 * - default export is the plugin factory (opencode's plugin loader accepts
 *   default exports as the server entrypoint).
 * - we only forward `message.part.updated`. that's where the user-visible
 *   subagent activity (tool calls, text, step transitions) lives. add more
 *   event types here if the parent needs them.
 * - JSON.stringify+single write keeps the line atomic up to PIPE_BUF (4KB on
 *   Linux). longer parts may interleave with concurrent stdout writers; the
 *   parser tolerates non-JSON lines (logs them at debug) so a torn line is a
 *   missed event, not a crash.
 */
export const KATAK_OPENCODE_PLUGIN_SOURCE = `// AUTOGENERATED by Pullfrog. do not edit; it'll be overwritten on the next run.
// surfaces opencode subagent activity that the CLI's run-loop discards. see
// action/agents/opencodePlugin.ts in pullfrog/app for why this exists. lives
// inside the per-run tmpdir (XDG_CONFIG_HOME/opencode/plugin/), never inside
// the user's working tree. the subagent gate ships as a separate plugin
// (pullfrog-subagent-gate.ts).

const KATAK_BUS_EVENT_TYPE = ${JSON.stringify(KATAK_BUS_EVENT_TYPE)};

// orchestratorSessionID locks to the first sessionID we observe on the bus
// (\`message.part.updated\`). opencode's run command creates exactly one
// top-level session before any subagent is dispatched, and the orchestrator
// emits at least one event before any subagent does — so first-seen-wins
// captures the orchestrator; every subagent part has a non-matching
// sessionID.
let orchestratorSessionID: string | undefined;

function isOrchestratorTaskDispatch(part: {
  type?: string;
  tool?: string;
  state?: { status?: string };
} | undefined): boolean {
  if (!part || part.type !== "tool") return false;
  if (part.tool !== "task") return false;
  // only forward at status="running" (not "pending"). at pending the
  // state.input is still {} — the orchestrator has emitted the part shell
  // but the LLM hasn't filled in description/subagent_type/prompt yet. by
  // running, input is populated and recordTaskDispatch can derive the lens
  // label correctly.
  return part.state?.status === "running";
}

export default async function pullfrogEventsPlugin() {
  return {
    event: async (input: {
      event: {
        type: string;
        properties?: {
          part?: {
            sessionID?: string;
            type?: string;
            tool?: string;
            state?: { status?: string };
          };
        };
      };
    }) => {
      const event = input?.event;
      if (!event || typeof event !== "object") return;
      if (event.type !== "message.part.updated") return;
      const part = event.properties?.part;
      const sessionID = part?.sessionID;
      if (typeof sessionID !== "string" || sessionID.length === 0) return;
      if (orchestratorSessionID === undefined) orchestratorSessionID = sessionID;

      if (sessionID === orchestratorSessionID) {
        // skip orchestrator events EXCEPT early task dispatches.
        if (!isOrchestratorTaskDispatch(part)) return;
      }

      try {
        const line = JSON.stringify({
          type: KATAK_BUS_EVENT_TYPE,
          bus_event: event,
        });
        process.stdout.write(line + "\\n");
      } catch {
        // a circular reference or BigInt etc. would throw; swallow rather
        // than letting a single bad event take down the plugin.
      }
    },
  };
}
`;

/**
 * Standalone subagent gate plugin written to
 * `<XDG_CONFIG_HOME>/opencode/plugin/pullfrog-subagent-gate.ts`. Installed by
 * BOTH opencode harnesses (the legacy `opencode.ts` and the active in-process
 * `opencode.ts`) — the gate is the load-bearing security fence, so it ships
 * independently of the events re-emitter above (which v2 doesn't need).
 *
 * Hard-blocks state-mutating MCP tool calls originating from a subagent
 * session via `tool.execute.before`, complementing the runtime backstops from
 * PR #796 (action/mcp/checkout.ts, action/mcp/git.ts). Deny-list source of
 * truth: `action/agents/subagentToolGates.ts`.
 *
 * Also hard-blocks the native `bash` tool for EVERY session. bash stays in the
 * tool list because Zen's free tier rejects a request without it (2026-09-17);
 * `permission.bash: "ask"` is the fail-closed backstop should this plugin ever
 * not load. see wiki/security.md.
 */
export function buildOpencodeSubagentGateSource(deniedTools: readonly string[]): string {
  return `// AUTOGENERATED by Pullfrog. do not edit; it'll be overwritten on the next run.
// hard-blocks state-mutating MCP tool calls from opencode subagents (PR
// following pullfrog/app#796 — see action/agents/subagentToolGates.ts). see
// action/agents/opencodePlugin.ts in pullfrog/app for why this exists. lives
// inside the per-run tmpdir (XDG_CONFIG_HOME/opencode/plugin/), never inside
// the user's working tree.

// embedded at template-render time so the plugin source has no imports. the
// denied set is derived from each tool's \`mutates\` flag — see
// action/agents/subagentToolGates.ts.
const SUBAGENT_DENIED_TOOLS = new Set(${JSON.stringify(deniedTools)});

// opencode presents MCP tools as \`pullfrog_<bare>\`; strip that to compare
// against the canonical bare names in SUBAGENT_DENIED_TOOLS. native tools
// (read, write, bash, task, etc.) lack the prefix and never match the deny
// list anyway.
function stripPullfrogPrefix(toolName: string): string {
  if (toolName.startsWith("pullfrog_")) return toolName.slice("pullfrog_".length);
  return toolName;
}

// orchestratorSessionID locks to the first sessionID we observe on
// \`tool.execute.before\`. the orchestrator must invoke a tool (e.g. its
// \`task\` dispatch) before any subagent session exists, so first-seen-wins
// always captures the orchestrator; every subagent call therefore has a
// non-matching sessionID and is subject to the deny check.
let orchestratorSessionID: string | undefined;

export default async function pullfrogSubagentGatePlugin() {
  return {
    "tool.execute.before": async (
      input: { tool?: string; sessionID?: string; callID?: string },
      _output: { args?: Record<string, unknown> }
    ) => {
      // input: { tool, sessionID, callID } — confirmed against
      // anomalyco/opencode packages/opencode/src/session/tools.ts which
      // calls plugin.trigger("tool.execute.before", { tool, sessionID,
      // callID }, { args }). throwing here surfaces as a tool error to the
      // model (Effect's run.promise propagates the rejection through the
      // AI SDK's tool-runtime), so the subagent sees a denial and can
      // pick a different action.
      const sessionID = typeof input?.sessionID === "string" ? input.sessionID : "";
      const tool = typeof input?.tool === "string" ? input.tool : "";
      // above the sessionID check: the bash block must never depend on a
      // session id being present.
      if (tool === "bash") {
        throw new Error("the native bash tool is disabled in Pullfrog runs.");
      }
      if (!sessionID || !tool) return;
      if (orchestratorSessionID === undefined) orchestratorSessionID = sessionID;
      if (sessionID === orchestratorSessionID) return;
      const bare = stripPullfrogPrefix(tool);
      if (!SUBAGENT_DENIED_TOOLS.has(bare)) return;
      throw new Error(
        "subagent attempted to call denied tool '" + bare + "'. " +
        "subagents share the orchestrator's in-process working tree and toolState; " +
        "state-changing MCP tools (checkout_pr, push_branch, create_pull_request_review, " +
        "report_progress, etc.) are reserved for the orchestrator. " +
        "report findings back to the orchestrator and let it perform the mutation."
      );
    },
  };
}
`;
}
